# Generated by Django 5.2 on 2025-04-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CorporateFiling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=50)),
                ("subject", models.TextField()),
                ("announcement_date", models.DateField()),
                ("details", models.TextField(blank=True, null=True)),
                ("broadcast_datetime", models.DateTimeField(blank=True, null=True)),
                ("receipt_datetime", models.DateTimeField(blank=True, null=True)),
                ("dissemination_datetime", models.DateTimeField(blank=True, null=True)),
                ("difference", models.CharField(blank=True, max_length=50, null=True)),
                ("attachment_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
