# Generated by Django 5.2 on 2025-04-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240321_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporatefiling',
            options={'ordering': ['-filing_date']},
        ),
        migrations.RemoveField(
            model_name='corporatefiling',
            name='attachment_url',
        ),
        migrations.RemoveField(
            model_name='corporatefiling',
            name='broadcast_datetime',
        ),
        migrations.RemoveField(
            model_name='corporatefiling',
            name='details',
        ),
        migrations.RemoveField(
            model_name='corporatefiling',
            name='difference',
        ),
        migrations.RemoveField(
            model_name='corporatefiling',
            name='dissemination_datetime',
        ),
        migrations.RemoveField(
            model_name='corporatefiling',
            name='receipt_datetime',
        ),
        migrations.AddField(
            model_name='corporatefiling',
            name='filing_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corporatefiling',
            name='pdf_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='corporatefiling',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='corporatefiling',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='corporatefiling',
            index=models.Index(fields=['symbol'], name='app_corpora_symbol_ae7f52_idx'),
        ),
        migrations.AddIndex(
            model_name='corporatefiling',
            index=models.Index(fields=['filing_date'], name='app_corpora_filing__913171_idx'),
        ),
    ]
