# Generated by Django 5.2 on 2025-04-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_corporatefiling_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatefiling',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
