# Generated by Django 5.2 on 2025-04-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_corporatefiling_category_corporatefiling_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporatefiling",
            name="AMC_scheme_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="corporatefiling",
            name="broadcast_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="corporatefiling",
            name="difference",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="corporatefiling",
            name="dissemination",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="corporatefiling",
            name="receipt_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
