# Generated by Django 5.2 on 2025-04-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_corporatefiling_amc_scheme_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corporatefiling",
            name="broadcast_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="corporatefiling",
            name="dissemination",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="corporatefiling",
            name="receipt_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
