# Generated by Django 5.2 on 2025-04-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_corporatefiling_broadcast_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KiteToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=200)),
                (
                    "public_token",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "request_token",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
