# Generated by Django 5.2 on 2025-04-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_kitetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_token', models.BigIntegerField()),
                ('exchange_token', models.BigIntegerField()),
                ('tradingsymbol', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('last_price', models.FloatField()),
                ('expiry', models.DateField()),
                ('strike', models.FloatField()),
                ('tick_size', models.FloatField()),
                ('lot_size', models.IntegerField()),
                ('instrument_type', models.CharField(max_length=10)),
                ('segment', models.CharField(max_length=20)),
                ('exchange', models.CharField(max_length=10)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('interval', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
