# Generated by Django 5.2 on 2025-04-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_instrumentdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentdetails",
            name="exchange",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="instrumentdetails",
            name="instrument_type",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="instrumentdetails",
            name="interval",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="instrumentdetails",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="instrumentdetails",
            name="segment",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="instrumentdetails",
            name="tradingsymbol",
            field=models.CharField(max_length=200),
        ),
    ]
