# Generated by Django 5.2 on 2025-04-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_instrumentdetails_exchange_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentdetails",
            name="expiry",
            field=models.DateField(blank=True, null=True),
        ),
    ]
