# Generated by Django 5.2 on 2025-04-24 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_alter_instrumentdetails_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentdetails",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instrumentdetails",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
