# Generated by Django 5.2 on 2025-05-09 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_instrumentdetails_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalOHLC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.BigIntegerField()),
                ("interval", models.CharField(default="day", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterModelOptions(
            name="instrumentdetails",
            options={"ordering": ["-last_price"]},
        ),
        migrations.RemoveField(
            model_name="instrumentdetails",
            name="close",
        ),
        migrations.RemoveField(
            model_name="instrumentdetails",
            name="high",
        ),
        migrations.RemoveField(
            model_name="instrumentdetails",
            name="interval",
        ),
        migrations.RemoveField(
            model_name="instrumentdetails",
            name="low",
        ),
        migrations.RemoveField(
            model_name="instrumentdetails",
            name="open",
        ),
        migrations.AlterField(
            model_name="instrumentdetails",
            name="tradingsymbol",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name="instrumentdetails",
            index=models.Index(
                fields=["tradingsymbol"], name="app_instrum_trading_f5f864_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instrumentdetails",
            index=models.Index(
                fields=["last_price"], name="app_instrum_last_pr_99b02e_idx"
            ),
        ),
        migrations.AddField(
            model_name="historicalohlc",
            name="instrument",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.instrumentdetails"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="historicalohlc",
            unique_together={("instrument", "timestamp", "interval")},
        ),
    ]
