# Generated by Django 5.2 on 2025-04-30 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_instrumentdetails_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrumentdetails",
            name="close",
        ),
        migrations.RemoveField(
            model_name="instrumentdetails",
            name="high",
        ),
        migrations.RemoveField(
            model_name="instrumentdetails",
            name="interval",
        ),
        migrations.RemoveField(
            model_name="instrumentdetails",
            name="low",
        ),
        migrations.RemoveField(
            model_name="instrumentdetails",
            name="open",
        ),
        migrations.CreateModel(
            name="HistoricalOHLC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.BigIntegerField()),
                ("interval", models.CharField(default="day", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.instrumentdetails",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "unique_together": {("instrument", "timestamp", "interval")},
            },
        ),
    ]
